FROM node:22.8.0-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openssl \
    procps \
    && npm install -g @nestjs/cli@10.4.8 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app

RUN chown -R node:node /home/node/app

USER node

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node . .

EXPOSE 3001

CMD ["sh", "-c", "npm run migration:run && npm start"]
